apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - api-gateway.yaml
  - order-service.yaml
  - payment-service.yaml
  - inventory-service.yaml
  - notification-service.yaml
  - hpa.yaml
  - network-policy.yaml
  - pdb.yaml
