apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: kafka-spring
type: Opaque
stringData:
  API_GATEWAY_API_KEY: local-dev-key
  ORDER_DB_URL: jdbc:postgresql://postgres-order:5432/orderdb
  ORDER_DB_USERNAME: myuser
  ORDER_DB_PASSWORD: mypassword
  PAYMENT_DB_URL: jdbc:postgresql://postgres-payment:5432/paymentdb
  PAYMENT_DB_USERNAME: myuser
  PAYMENT_DB_PASSWORD: mypassword
  INVENTORY_DB_URL: jdbc:postgresql://postgres-inventory:5432/inventorydb
  INVENTORY_DB_USERNAME: myuser
  INVENTORY_DB_PASSWORD: mypassword
