{
  "type": "record",
  "name": "OrderCreatedEvent",
  "namespace": "com.example.events",
  "fields": [
    { "name": "orderId", "type": "string" },
    { "name": "productName", "type": "string" },
    { "name": "quantity", "type": "int" },
    { "name": "amount", "type": "string" },
    { "name": "customerEmail", "type": "string" },
    { "name": "eventId", "type": "string" },
    { "name": "correlationId", "type": "string" },
    { "name": "causationId", "type": "string" },
    { "name": "occurredAt", "type": "string" },
    { "name": "producer", "type": "string" },
    { "name": "schemaVersion", "type": "string" }
  ]
}
