apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-spring
resources:
  - ../../k8s
  - infra.yaml
images:
  - name: kafka-springboot/api-gateway
    newName: ghcr.io/bms1995/kafka-springboot/api-gateway
    newTag: latest
  - name: kafka-springboot/order-service
    newName: ghcr.io/bms1995/kafka-springboot/order-service
    newTag: latest
  - name: kafka-springboot/payment-service
    newName: ghcr.io/bms1995/kafka-springboot/payment-service
    newTag: latest
  - name: kafka-springboot/inventory-service
    newName: ghcr.io/bms1995/kafka-springboot/inventory-service
    newTag: latest
  - name: kafka-springboot/notification-service
    newName: ghcr.io/bms1995/kafka-springboot/notification-service
    newTag: latest
replicas:
  - name: api-gateway
    count: 1
  - name: order-service
    count: 1
  - name: payment-service
    count: 1
  - name: inventory-service
    count: 1
  - name: notification-service
    count: 1
patches:
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: Deployment
      name: api-gateway|order-service|payment-service|inventory-service|notification-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
